version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_DB_HOST: db
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: wordpress_local
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: wordpress_db_password
    ports:
      - "3306:3306"
    platform: linux/amd64

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-apache
    volumes:
      - db_data:/var/lib/mysql
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./wp-config.php:/var/www/html/wp-config.php
    ports:
      - "8011:80"
    restart: always
    environment:
      PHP_POST_MAX_SIZE: 64M
      PHP_MEMORY_LIMIT: 256M
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: dbpassword
      UPLOAD_LIMIT: 64M
    ports:
      - "8012:80"
    restart: always
    platform: linux/amd64

volumes:
  db_data: {}
